services: 
  api: 
    # Build the FastAPI application from the Dockerfile. 
    build: . 

    # Map the host port to the FastAPI container port. 
    ports: 
      - "8000:8000"

    # start the API after the database container is started. 
    depends_on: 
      - db 

  db: 
    # Use official PostgreSQL image. 
    image: postgres:17 

    # Set PostgreSQL environment variables.
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: mypassword 
      POSTGRES_DB: library_api 

    # Persist PostgreSQL data between container restarts. 
    volumes: 
      - postgres_data:/var/lib/postgresql/data 

    # Expose PostgreSQL to the host machine. 
    ports: 
      - "5432:5432"

volumes: 
  postgres_data: 
  

