"""create books table

Revision ID: 58bb0704ec38
Revises:
Create Date: 2026-08-31 10:29:42.803583

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "58bb0704ec38"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("serial_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("is_borrowed", sa.Boolean(), nullable=True),
        sa.Column("borrowed_at", sa.DateTime(), nullable=True),
        sa.Column("user_card_number", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("serial_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books")
    # ### end Alembic commands ###
